spring.application.name=alumni-searcher
spring.datasource.url=jdbc:postgresql://localhost:5432/alumni_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# PhantomBuster Properties
phantombuster.api.key=ay5ZwiBiPLMBb3mJvInzSkg18cicJmWBfJJ9w49PjJo
phantombuster.agent.id=3583985263656420
phantombuster.session.cookie=AQEDAUTRGqQCuJ28AAABnMLwuzMAAAGc5v0_M1YAptXuK4Hm0yjGDtq9u0xWyIpXST4kYyJ3he1Gdh74pD-m19uamKTvVlbTmyWKrEtLJ3xfCONf4xmWvLmKO9sY4xj59gH8pxYupqBK30rQjrnb8gvd